title: Margot Neyret
email: margot@neyret.me
description: 'Margot Neyret - Postdoctoral researcher, Senckenberg Gesellschaft für Naturforschung, Frankfurt, Germany'
baseurl: ''
url: ''
twitter_username: ''
github_username: mneyret
markdown: kramdown
plugins:
  - jekyll-admin
kramdown:
  parse_block_html: true
